version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nutritrack-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: nutritrack-backend
    restart: always
    env_file:
      - ./backend/.env.example
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nutritrack-db
    restart: always
    environment:
      POSTGRES_DB: nutritrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql

  nginx:
    image: nginx:alpine
    container_name: nutritrack-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
